In [1]:
%matplotlib inline
from matplotlib import lines as mlines
from matplotlib import pyplot as plt

import numpy as np

def fracdiff(alt, fid):
    return (alt-fid)/fid
from halotools.empirical_models import PrebuiltHodModelFactory

/home/mj/.local/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)


In [17]:
model = PrebuiltHodModelFactory('hearin15', threshold = 10.6, redshift = 0., 
                        central_assembias_strength = 0, 
                        satellite_assembias_strength = 0)
model.param_dict['scatter_model_param1'] = 0.4 # This is the "fiducial" scatter used throughout the paper
baseline_model = PrebuiltHodModelFactory('leauthaud11', threshold = 10.6, redshift = 0.)
baseline_model.param_dict['scatter_model_param1'] = 0.4

In [18]:
model.populate_mock()

In [19]:
model.mock.compute_galaxy_matter_cross_clustering(rbins = R*10**-3.)

(array([ 0.0354  ,  0.043235,  0.052805,  0.0645  ,  0.07878 ,  0.09622 ,
         0.117525,  0.143545,  0.175325,  0.214145,  0.26156 ,  0.31947 ,
         0.3902  ,  0.47659 ,  0.58211 ,  0.71099 ,  0.868405,  1.060675,
         1.29551 ,  1.582335,  1.932665,  2.360565,  2.8832  ]),
 array([  8.75928137e+03,   5.86086876e+03,   3.57622029e+03,
          2.40928832e+03,   1.53088073e+03,   1.02093480e+03,
          6.62567960e+02,   4.22434223e+02,   2.52496460e+02,
          1.60842291e+02,   9.90979974e+01,   6.13197229e+01,
          3.76925864e+01,   2.40252343e+01,   1.64036177e+01,
          1.10814372e+01,   7.81023787e+00,   5.85379762e+00,
          4.53675933e+00,   3.44654559e+00,   2.55399415e+00,
          1.90037107e+00,   1.42916330e+00]))

In [14]:
R = np.array([31.87,38.93,47.54,58.07,70.93,86.63,105.81,129.24,157.85,192.80,235.49,287.63,351.31,429.09,524.09 ,640.13 
,781.85 
,954.96 
,1166.39 
,1424.63 
,1740.04,2125.29,2595.84,3170.56])

In [12]:
xi_gm = np.array([-25.63,76.67,79.43,28.00,18.30,28.00,26.59,11.41,21.32,1.61,7.15,1.19,-2.55,5.88,1.33,-0.21,-1.26 ,2.61,0.54,
3.27,2.26,0.76,0.51,0.49])

In [20]:
model.param_dict

{'alphasat': 1.0,
 'bcut': 1.47,
 'betacut': -0.13,
 'betasat': 0.859,
 'bsat': 10.62,
 u'scatter_model_param1': 0.4,
 u'smhm_beta_0': 0.43,
 u'smhm_beta_a': 0.18,
 u'smhm_delta_0': 0.56,
 u'smhm_delta_a': 0.18,
 u'smhm_gamma_0': 1.54,
 u'smhm_gamma_a': 2.52,
 u'smhm_m0_0': 10.72,
 u'smhm_m0_a': 0.59,
 u'smhm_m1_0': 12.35,
 u'smhm_m1_a': 0.3}

In [31]:
model.mock.compute_galaxy_clustering()

(array([  0.12239095,   0.17719995,   0.25655347,   0.37144299,
          0.53778224,   0.77861137,   1.12728837,   1.63210958,
          2.36299934,   3.42119545,   4.95327193,   7.17144145,
         10.38294952,  15.03263208]),
 array([ -0.14747511,  -0.29772983,   4.78497345,  10.71142442,
          9.26535586,   6.51158463,   4.12254192,   2.4676225 ,
          1.42187277,   0.82640716,   0.49090503,   0.28025908,
          0.15694177,   0.08513456]))

In [30]:
model.mock.compute_galaxy_matter_cross_clustering()

(array([  0.12239095,   0.17719995,   0.25655347,   0.37144299,
          0.53778224,   0.77861137,   1.12728837,   1.63210958,
          2.36299934,   3.42119545,   4.95327193,   7.17144145,
         10.38294952,  15.03263208]),
 array([  5.99886482e+02,   2.48900884e+02,   1.01236245e+02,
          4.22471762e+01,   1.85972465e+01,   9.34660317e+00,
          5.49691910e+00,   3.27165108e+00,   1.87976370e+00,
          1.09358875e+00,   6.38424225e-01,   3.62620861e-01,
          2.02166122e-01,   1.03976748e-01]))

In [42]:
model = PrebuiltHodModelFactory('zheng07')
model.populate_mock()

In [45]:
(250**3.)*model.mock.number_density*50
#for i in range(10):
    
#  model.populate_mock()
#  print model.mock.compute_galaxy_clustering()

3678650.0

(array([  0.12239095,   0.17719995,   0.25655347,   0.37144299,
          0.53778224,   0.77861137,   1.12728837,   1.63210958,
          2.36299934,   3.42119545,   4.95327193,   7.17144145,
         10.38294952,  15.03263208]),
 array([ -1.        ,  -0.77840244,   3.30798441,  11.70320121,
         11.04187656,   7.9857014 ,   5.04037702,   3.02146281,
          1.74846067,   1.01618687,   0.60632803,   0.34254218,
          0.19159335,   0.0997026 ]))